#uses omake to build and test on ubuntu only

name: build-and-test
on:
  - pull_request

jobs:
  build:
     runs-on: ubuntu-latest

     env:
       OPAMJOBS: 2
       OPAMRETRES: 8

     steps:
         - name: Checkout code
           uses: actions/checkout@v2
           with:
             submodules: recursive

         - name: Install OCaml
           uses: avsm/setup-ocaml@v1
           with:
             ocaml-version: 4.07.1

         - name: Pin OASIS
           run: opam pin add oasis https://github.com/BinaryAnalysisPlatform/oasis.git

         - name: Pin BAP
           run: opam pin add bap . --no-action

         - name: Install system dependencies
           run: opam depext bap

         - name: Install opam dependencies
           run: opam install bap --deps-only

         - name: Configure BAP
           run: opam exec -- ./configure-omake

         - name: Build BAP
           run: opam exec -- make

         - name: Install BAP
           run: opam exec -- make reinstall

         - name: Run Unit Tests
           run: opam exec -- make test

         - name: Run Functional Tests
           run: pam exec -- make check

         - name: Run BIL verification tool
           run: |
             opam pin add bap-veri testsuite/veri/bap-veri/ -y
             opam exec -- make -C testsuite veri

         - uses: actions/upload-artifact@v2
           if: ${{ always() }}
           with:
             name: bap-log
             path: /tmp/bap/log

         - uses: actions/upload-artifact@v2
           if: ${{ always() }}
           with:
             name: unit-tests-log
             path: oUnit-*.log

         - uses: actions/upload-artifact@v2
           if: ${{ always() }}
           with:
             name: fun-tests-log
             path: testsuite/*.log
