name: Debian-testing

on:
 schedule:
    - cron: '0 0 * * WED'

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@master

     - name: Build on Debian Testing
       uses: docker/build-push-action@v1
       with:
         push: false
         dockerfile: docker/debian/testing/Dockerfile
